# Generated by Django 3.1.2 on 2021-04-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(upload_to='', verbose_name='Картинка'),
        ),
    ]
