# Generated by Django 3.1.2 on 2021-04-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_auto_20210407_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(upload_to='Posts/static/Posts/images', verbose_name='Картинка'),
        ),
    ]
