# Generated by Django 3.1.2 on 2021-04-06 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, verbose_name='Логин')),
            ],
            options={
                'verbose_name': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='UserTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_points', models.IntegerField(verbose_name='Результирующий балл')),
                ('check_status', models.BooleanField(verbose_name='Статус проверки')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tests.test', verbose_name='Тест')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tests.customuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Тесты пользователя',
            },
        ),
        migrations.CreateModel(
            name='UserTestTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='Тип ответа')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('task_statement', models.TextField(verbose_name='Формулировка задания')),
                ('points', models.IntegerField(verbose_name='Баллы задания')),
                ('user_points', models.IntegerField(verbose_name='Полученные баллы')),
                ('check_status', models.BooleanField(verbose_name='Статус проверки')),
                ('user_test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tests.usertest')),
            ],
            options={
                'verbose_name': 'Задание пользователя',
                'verbose_name_plural': 'Задания пользователя',
            },
        ),
        migrations.CreateModel(
            name='TestTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='Тип ответа')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('task_statement', models.TextField(verbose_name='Формулировка задания')),
                ('points', models.IntegerField(verbose_name='Баллы')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tests.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
    ]
