# Generated by Django 3.1.2 on 2021-04-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertest',
            name='user_id',
        ),
        migrations.AddField(
            model_name='test',
            name='picture',
            field=models.ImageField(default=None, upload_to='Tests/static/Tests/images', verbose_name='Картинка'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
