# Generated by Django 3.1.2 on 2021-04-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tests', '0003_usertest_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertest',
            options={'verbose_name': 'Тест пользователя', 'verbose_name_plural': 'Тесты пользователя'},
        ),
        migrations.AddField(
            model_name='testtask',
            name='correct_answer',
            field=models.TextField(default=None, verbose_name='Правильный ответ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertesttask',
            name='correct_answer',
            field=models.TextField(default=None, verbose_name='Правильный ответ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertesttask',
            name='user_answer',
            field=models.TextField(default=None, verbose_name='Ответ пользователя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertesttask',
            name='user_file',
            field=models.FileField(default=None, upload_to='', verbose_name='Файл ответа'),
            preserve_default=False,
        ),
    ]
