# Generated by Django 3.1.2 on 2021-04-11 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tests', '0004_auto_20210409_1343'),
        ('Tests', '0004_auto_20210410_1826'),
    ]

    operations = [
    ]
