# Generated by Django 3.1.2 on 2021-04-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tests', '0005_merge_20210411_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='picture',
            field=models.ImageField(upload_to='Tests/images', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='usertesttask',
            name='type',
            field=models.CharField(choices=[('TE', 'Вручную'), ('CO', 'Автоматически')], max_length=20, verbose_name='Тип ответа'),
        ),
    ]
