# Generated by Django 3.1.2 on 2021-04-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tests', '0006_auto_20210411_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='picture',
            field=models.ImageField(upload_to='Tests/static/Tests/images', verbose_name='Картинка'),
        ),
    ]
