# Generated by Django 3.1.2 on 2021-04-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tests', '0007_auto_20210411_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertesttask',
            name='user_file',
            field=models.FileField(upload_to='Tests/static/Tests/user_files', verbose_name='Файл ответа'),
        ),
    ]
