# Generated by Django 3.1.2 on 2021-04-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tests', '0008_auto_20210411_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='max_points',
            field=models.IntegerField(null=True, verbose_name='Максимальный балл'),
        ),
    ]
