# Generated by Django 3.1.2 on 2021-04-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tests', '0009_test_max_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertesttask',
            name='user_points',
            field=models.IntegerField(default=0, verbose_name='Полученные баллы'),
        ),
    ]
